### ISSUE TITLE
The snp allele information in the file called 'Genome wide significant eQTL snp-feature pairs'

### ISSUE THREAD

**Issue by Lee211** [LieberInstitute/brainseq_phase2#31]
i cannot find the snp allele information (i.e. A1/A2, or ref/alt) in the file called 'Genome wide significant eQTL snp-feature pairs'. Are these data  available?

**Comment by lcolladotor** [comment]
Hi @Lee211,

Sorry that I missed this. We have that information in another file described in https://github.com/LieberInstitute/brainseq_phase2/tree/master/browser#snp-information. Let me check what's the best way for us to share it.

Best,
Leonardo

**Comment by lcolladotor** [comment]
Hi @Lee211,

In https://github.com/LieberInstitute/brainseq_phase2/commit/48edebd6b5c739aa313dcd74878af94fb7d1b756 I updated our documentation about these files. Also, the SNP annotation file is available [here](https://libd-brainseq2.s3.us-east-2.amazonaws.com/BrainSeqPhaseII_snp_annotation.txt.gz) which has the columns `newref` (lower case for `newRef`) and `newcount` (lower case for `newCount`) which are the columns you wanted. You can match the different tables using the `snp` column from the files in `SupplementaryTable15_eQTL.tar.gz` and the SNP annotation table.

Best,
Leo
