### ISSUE TITLE
phenotype data

### ISSUE THREAD

**Issue by xiangboyulan** [LieberInstitute/brainseq_phase2#32]
Hi,
I obtained the phenotype data (methprop_pd.Rdata) through the web: http://eqtl.brainseq.org/phase2/, but found that Age is 29.98 or 69.07, could you give me more information about Race (CAUC or  AA or AS)? 

Thanks!

**Comment by andrewejaffe** [comment]
CAUC = european / caucasian
AA = african american
AS = asian

**Comment by xiangboyulan** [comment]
Hi Andrew,
Age
64.08
62.61
29.98
65.26
32.35
69.07
48.1
50.28
47.01
49.26
35.21
54.43
50
24.79
58.48
22.09
60.75
47.35
35.82
25.59
Why do age have two decimal places?
Thanks!

Bo

**Comment by xiangboyulan** [comment]
What preprocessing has been done for rse_gene_unfiltered.Rdata file? 

Thanks a lot!

Bo

**Comment by andrewejaffe** [comment]
a) It's age in years...so a donor who was 60 years and 1 month is 60.08
b) no preprocessing, its just combining featureCounts output across samples
